### ISSUE TITLE
AnsibleUndefinedVariable error while deploying SKC library

### ISSUE THREAD

**Issue by manju956** [intel-secl/skc_library#1]
I am trying to bring up SKC setup. Building isecl binaries was successul, however while deploying the binaries on multiple hosts, below issue is observed.

**_**_T**ASK [ansible-role : ISECL - SKC LIBRARY | Copy Create Roles configuration file] ************************************************************************************
fatal: [192.168.1.33]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'aas_enterprise' is undefined"}**_**_**

I have set ip of enterprise in /etc/ansible/hosts
[Enterprise]
192.168.1.33

Is this a known issue? If so, any available solutions or workarounds?

**Comment by manju956** [comment]
Ok, is it possible to extract ip address from the system and populate if default interface is not set?

**Comment by vinit-intel** [comment]
You can run below command on ansible machine and check if all populated values are correct:
_ansible -m setup <node ip>_

**Comment by manju956** [comment]
default ipv4 address:
"ansible_default_ipv4": {
            "address": "192.168.1.33",
            "alias": "eno1",
            "broadcast": "192.168.1.255",
            "gateway": "192.168.1.1",
            "interface": "eno1",
            "macaddress": "94:c6:91:1c:a6:94",
            "mtu": 1500,
            "netmask": "255.255.255.0",
            "network": "192.168.1.0",
            "type": "ether"
        },

ansible_fqdn:
"ansible_fqdn": "ca.org2.example.com",
        "ansible_hostname": "chaos-desktop",
        "ansible_hostnqn": "",
        "ansible_interfaces": [
            "docker0",
            "wlp58s0",
            "docker_gwbridge",
            "lo",
            "eno1"
        ],
        "ansible_is_chroot": false,
        "ansible_iscsi_iqn": "",

**Comment by vinit-intel** [comment]
It seems your /etc/hosts file has multiple host entries for same IP. That's why ansible is fetching different-different values as seen in output below:

"ansible_fqdn": "ca.org2.example.com",
"ansible_hostname": "chaos-desktop",

**Comment by vinit-intel** [comment]
As discussed, after this change you are not seeing reported issue. Also this issue is not related with isecl ansible role. So closing this issue.
